---
title: "Statistical Consulting"
---

<!-- 
consulting and pricing example
https://www.statistical-coaching.ch/consulting_data_analysis/
-->

I have consulted over 200 clients, primarily PhD and master's students along with industry professionals. Regular discussions of these cases in the Seminar for Statistics at ETH Zurich have broadened my understanding of the statistical landscape and deepened my mathematical insights. This comprehensive experience means I can deliver effective solutions for most statistical challenges I encounter.

Want to challenge me? Contact me via email at [stat.consulting.graz@gmail.com](mailto:stat.consulting.graz@gmail.com) to have a **free** 30min initial chat via zoom.

## Services

### Research Planning & Support
- Research question formulation and statistical hypotheses
- Study preregistration
- Experimental design selection
- Sample size and power analysis, requiring:
  - Clear statistical hypotheses
  - Defined experimental design
  - Planned analysis approach
- Response to reviewer comments
- Individual coaching
- Custom workshops and seminars

### Statistical Modeling & Analysis
- Multiple regression
- ANOVA/ANCOVA/MANOVA (including repeated measures)
- Mixed effects models (LMM/GLMM)
- Generalized linear models (GLM)
- Generalized additive models (GAM)
- Structural equation models (SEM)
- Path and mediation analysis
- Causal inference
- Time series analysis
- Gaussian process regression
- Multivariate analysis
- Bootstrap and permutation tests
- Non-parametric tests
- Random forests

### Reproducible Research & Reporting:
- R programming (Zurich R Courses lecturer)
- Linux, bash, git, and Docker
- Documentation formats:
  - Interactive dashboards (Shiny)
  - Reports (Rmarkdown)
  - Reproducible manuscripts (example XXX)
  - Quarto websites (like this one)

## Pricing
- **Free 30-minute consultation** via Zoom to discuss your project
- **Industry/Institutional**: 170 CHF/hour (140 CHF/hour after 10 hours)
- **Students**: 140 CHF/hour (100 CHF/hour after 5 hours)

Contact: [stat.consulting.graz@gmail.com](mailto:stat.consulting.graz@gmail.com)
