---
# layout: post
title: '`r ({
  .proj_title <- base::gsub("_", " ", base::gsub("\\.[rqmarkdown]+", "", knitr::current_input(), ignore.case = TRUE));   stringr::str_to_title(.proj_title) })`'
author: Lukas Graz
date: '`r 2023-11-14`'
#abstract: MY FANCY ABSTRACT

# format:
#   pdf:
#     df-print: default
#     toc: false
#     toc-depth: 2
#     number-sections: false
#     colorlinks: true
#     fig-width: 6.5
#     fig-height: 4.5
#     keep-tex: true
#   html: {}
# knit: |
#   (function(input, ...) {
#     stop("not evaluated")
#     rmarkdown::render(
#       input,
#       output_file = paste0(
#         xfun::sans_ext(input), '-', Sys.Date(), '_XX.md'
#       ),
#       envir = globalenv()
#     )
#   })
---


```{r setup, cache=FALSE, echo=FALSE} 
# knitr::opts_chunk[['set']](cache = TRUE, autodep = TRUE)

knitr::opts_knit$set(base.dir = "~/Git/LGraz.github.io/", base.url = "/")
.proj_title <- base::gsub("_", " ", base::gsub("\\.[rqmarkdown]+", "", knitr::current_input(), ignore.case = TRUE))
knitr::opts_chunk$set(fig.path = paste0("assets/R-images/", .proj_title, "/"))



``` 


$$
E = m c ^2
$$

```{r load_packages, message = FALSE, warning = FALSE}
library(lmerTest)
```



```{r main}
plot(cars)
summary(cars)
```



